= AWS Glue
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

toc::[]


== Glue Streaming
. By default, AWS Glue processes and writes out data in 100-second windows.
. AWS Glue streaming jobs use checkpoints rather than job bookmarks to track the data that has been read.
. AWS Glue bills hourly for streaming ETL jobs while they are running.


[quote, AWS doc]
____
If you know the schema of the streaming data source, you can specify it in a Data Catalog table. If not, you can enable schema detection in the streaming ETL job. The job then automatically determines the schema from the incoming data.
____
How does schema detection in streaming ETL affect performance?


=== Streaming Limitations
. When using schema detection, you cannot perform joins of streaming data.

=== Streaming Notes
. AWS Glue streaming ETL jobs use checkpoints to keep track of the data that has been read. Therefore, a stopped and restarted job picks up where it left off in the stream. If you want to reprocess data, you can delete the checkpoint folder referenced in the script.




== References
. https://docs.aws.amazon.com/glue/latest/dg/add-job-streaming.html[Streaming ETL jobs in AWS Glue]